### ISSUE TITLE
[Feature Request] Upgrade Python to >3.6

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycon.tw#1028]
## Describe the solution you'd like
Python 3.6 is going to EOL later this year (2021) https://endoflife.date/python This latest CI build shows we are currently supporting our site with 3.6 officially https://github.com/pycontw/pycon.tw/runs/2876830688 .

We may want to upgrade python after the main conference event.

## Describe alternatives you've considered
We may also consider to upgrade python after talk proposals are announced.

**Comment by mattwang44** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [upgrade python](https://trello.com/c/Ca3oyOUf/61-upgrade-python)
