### ISSUE TITLE
[Review System] Clicked "Withdraw" button and a banner showed "Talk proposal with drawn", but the talk entry is not removed.

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycon.tw#1071]
## Description
To be honest I am not sure it's a bug or feature. I accidentally create a duplicate talk entry when submitting talks, and I would like to remove one of them. By clicking "Withdraw", I got a notification banner telling me that the talk proposal has been "withdrawn". However, I can still see the withdrawn talk proposal shown on my submitting dashboard.

## Steps to Reproduce
1. Login the proposal review system
2. Click `+New Talk Proposal`. Fill the necessary fields to create a proposal.
3. Click `+New Talk Proposal` again to create another one.
4. Click Withdraw button to withdraw one of them.

## Expected Behavior
The withdrawn proposal has been removed.

## Actual Behavior
The proposal still exists. The "Edit" button becomes "Reactivate".

**Screenshots**
The picture shows the status of the buttons now.
![Selection_045](https://user-images.githubusercontent.com/3217432/163382528-d88f7424-3e89-46f6-8940-8a2c2fae717b.png)

## More Information
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu Mate 18.04
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 100.0.4896.75 (Official Build) (64-bit)

## Additional context
The UI and design of the submitting system is so beautiful!

**Comment by mattwang44** [comment]
I believe it's a feature. If the submitters accidentally delete the wrong proposals, this feature gives them a chance to get them back. Also, the withdrawn proposals will not be sent to the review stage.

**Comment by tai271828** [comment]
Thanks for the elaboration. I will close this issue then.
