### ISSUE TITLE
[Deployment] Fail to build the Docker images

### ISSUE THREAD

**Issue by mattwang44** [pycontw/pycon.tw#1079]
## Description

Fail to build the Docker images from both `Dockerfile` and `dev.Dockerfile`:
- Cannot find the correct version of `psycopg2`.
- Cannot build `Pillow` successfully.

**Comment by mattwang44** [comment]
It turns out that this issue only happened on M1.

**Comment by josix** [comment]
This could be solved by adding `export DOCKER_DEFAULT_PLATFORM=linux/amd64`  to your environment. I think we don't need to modify Dockerfile and docker-compose.yml only for running on M1 machines.

**Comment by mattwang44** [comment]
@josix agreed, but how about adding some comments hinting M1 users to solve such issue?

**Comment by josix** [comment]
I added a checker in enter_dev_env.sh.to and set DOCKER_DEFAULT_PLATFORM to linux/amd64 when detecting the machine is arm64, please have a look, thanks! I'm not sure if there are other places that should notify users of this configuration, feel free to let me know if somewhere could be updated.

**Comment by josix** [comment]
I guess this is solved by #1082, right? @mattwang44

**Comment by mattwang44** [comment]
IIRC it does work on some of our M1s but adding `platform: x86_64` to each service defined in docker compose file seems to be a common solution (since im not sure how will this change affect other platforms, I didnt check-in this change to the repo).

**Comment by mattwang44** [comment]
let's close it for now
