### ISSUE TITLE
[Feature Request] Provide a new GET API for talk/tutorial listing by category

### ISSUE THREAD

**Issue by mattwang44** [pycontw/pycon.tw#1080]
## Description

To support [listing similar topics on the frontend](https://github.com/pycontw/pycontw-frontend/issues/246), a new API providing the talk data by the category is desired.

<img width="765" alt="image" src="https://user-images.githubusercontent.com/24987826/169095632-26d17b1d-a2fd-4643-a092-0169d72b6047.png">

**Comment by mattwang44** [comment]
@josix Are you able to manage this feature by the end of next weekend?

**Comment by josix** [comment]
Oh... Let me try for that. I'm facing the same issue as #1079 on my new laptop and I am still working on it.
