### ISSUE TITLE
[Bug Report]: The statistic dashboard for the reviewer got the wrong counting.

### ISSUE THREAD

**Issue by linooohon** [pycontw/pycon.tw#1086]
## Description
**Describe the bug**
The statistic dashboard for the reviewer got the wrong counting.

**Screenshots**
![pycontw_review_system](https://user-images.githubusercontent.com/65331756/176391663-88a85fb7-cb2d-40f5-888b-57f61d013377.jpg)

## Expected Behavior
The sum of 個人審查數據 should be the same as 已審查的演講提案.

**Comment by mattwang44** [comment]
closed by #1087
