### ISSUE TITLE
adopting the official codecov action

### ISSUE THREAD

**Issue by josix** [pycontw/pycon.tw#1126]
I'd suggest adopting the [official codecov action](https://github.com/codecov/codecov-action) in CI action.

_Originally posted by @mattwang44 in https://github.com/pycontw/pycon.tw/pull/1125#discussion_r1125441489_

**Comment by mattwang44** [comment]
我有稍微 survey 一下但沒時間嘗試
- 目前應該缺一份 [pytest-cov 產出的 coverage report (xml)](https://pytest-cov.readthedocs.io/en/latest/reporting.html) 讓 codecov 上傳，pytest 指令要改成同時可以產 report 並在 terminal 上 output report
- 覺得不用新增 .codecov.yml，看懂 codecov action 怎麼設定就好
