### ISSUE TITLE
[Schedule] The CCIP schedule datatime needs to be changed to UTC+8

### ISSUE THREAD

**Issue by tyuchx** [pycontw/pycon.tw#1148]
## Description

The CCIP schedule datatime needs to use UTC+8

## Expected Behavior

![Image](https://github.com/pycontw/pycon.tw/assets/6921552/8fb39756-ae6a-41fc-be28-e5143420fdea)

**Comment by uranusjr** [comment]
Sounds like a OPass client side bug then? Maybe the iOS client isn’t handling timezones correctly. Our API emits UTC time with timezone e.g. `2023-09-02T02:10:00+00:00`.

**Comment by uranusjr** [comment]
Fixed in OPass for iOS 4.2.4 (see linked issue above).
