### ISSUE TITLE
行為準則 Code of Conduct (CoC) - 後台

### ISSUE THREAD

**Issue by PenguinRun** [pycontw/pycon.tw#1159]
- 主要需求：修正後台中的 CoC 文案內容
- 發案組別：綜合
- 發案者： @gabriel0952 

文案內容：[2024 CoC 新版文案](https://docs.google.com/document/d/1iEmidfXZImg-f1di24aotiXOmo-gSHhtNTA_QoqxbLg/edit#heading=h.dhqtrv9uj5ao)

**Comment by rockleona** [comment]
@PenguinRun I think it's duplicated lol, see #1158

**Comment by rockleona** [comment]
@SivanYeh 我發現為甚麼沒有 pycontw-2024 了....
#1155
