### ISSUE TITLE
Sponsor 頁面只有英文版的

### ISSUE THREAD

**Issue by adrianliaw** [pycontw/pycon.tw#487]
目前如果連到 https://tw.pycon.org/2019/zh-hant/sponsor/sponsor/ （zh-Hant），顯示的內容是英文版的 Why Sponsorship，不確定是 bug 還是 feature

**Comment by jneo8** [comment]
等待贊助組的內容中

**Comment by bill0812** [comment]
已修改好中文版的部分，跟修改一點英文的內容，有 new 一個 pull requests， 要麻煩看看有沒有看到跟merge成功～

**Comment by jneo8** [comment]
fix in #494
