### ISSUE TITLE
Update 2019 sponsor 申請表單連結.

### ISSUE THREAD

**Issue by jneo8** [pycontw/pycon.tw#489]
New link

https://docs.google.com/forms/d/1QxpLZm1KOQ3cffJQM5wxeA1dadZSoViyGjNAx4VCdxY/edit

**Comment by freddy50806** [comment]
想再確認一下
所以要把現在這個2019表單
https://docs.google.com/forms/d/e/1FAIpQLScEIeCrTHNvwbdNbZt4nK1mteC6NzHtXgF5bVn1KTtR0_sorA/viewform
替換成這個嗎?
