### ISSUE TITLE
the formatting is off in mobile page

### ISSUE THREAD

**Issue by freddy50806** [pycontw/pycon.tw#516]
iphone 5/SE
![image](https://user-images.githubusercontent.com/14121801/55168897-ad96a080-51ae-11e9-92b4-30de7d5cdf1b.png)

Pixel 2XL iphone 6/7/8 plus
![image](https://user-images.githubusercontent.com/14121801/55168754-60b2ca00-51ae-11e9-9d94-2a30542b0810.png)

**Comment by josix** [comment]
The problem here is setting the width to 120px for cfp section and it is solved due to solving issue #518 .

**Comment by uranusjr** [comment]
I believe this is fixed now
