### ISSUE TITLE
Dependency version mismatch

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycon.tw#523]
During a fresh `pip install -r requirements.txt`:

```
django-picklefield 2.0 has requirement Django>=1.11, but you'll have django 1.10.4 which is incompatible.
```

django-picklefield is a dependency of django-q.

**Comment by shunghsiyu** [comment]
`django-picklefield` is now pinned to version 1.0.0 in f8bd64a58ac3d6b99231eaab1e311a9908b83878

**Comment by shunghsiyu** [comment]
However it's only pinned in `requirements/production.txt`... maybe it should be moved to somewhere else?

**Comment by uranusjr** [comment]
django-q is pinned in base.txt, so django-picklefield probably should as well.

**Comment by shunghsiyu** [comment]
I think we can close this now that #554 is merged
