### ISSUE TITLE
Where should we keep deployment documentations?

### ISSUE THREAD

**Issue by shunghsiyu** [pycontw/pycon.tw#533]
I attempted to add documentation on how to run the 2016 production server in README.md #528, but was later persuaded by @jneo8 to move the documentation into the wiki to avoid confusion.

After adding [Production Environment for the 2016 Website](https://github.com/pycontw/pycon.tw/wiki/Production-Environment-for-the-2016-Website) and [Production Environment for the 2017 Website](https://github.com/pycontw/pycon.tw/wiki/Production-Environment-for-the-2017-Website), however, I realize there is a lot of duplication, and probably more to come as we move on.

Any suggestion for better deployment documentation alternatives?

**Comment by shunghsiyu** [comment]
Two alternatives I can think of

1. [Put deployment documentation along with the code, e.g. `DEPLOY.md`](https://github.com/pycontw/pycon.tw/pull/528#issuecomment-482781358), as suggested by @uranusjr 
2. Keep the deployment documentation in a single wiki entry, and some how address the difference between each website

**Comment by jneo8** [comment]
Prefer 1, `DEPLOY.md`.

**Comment by shunghsiyu** [comment]
Now that `DEPLOY.md` is merged into master I think we can close this issue
