### ISSUE TITLE
Talk detail page glitch

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycon.tw#556]
Via Slack:

![image](https://user-images.githubusercontent.com/605277/59336964-26c77d80-8d32-11e9-9660-88429dc4ba5a.png)

似乎只有 Chrome 系的瀏覽器會壞，我在 Firefox 和 Safari 都正常。猜測猜是 `columns: 2;` 的實作 bug。

**Comment by freddy50806** [comment]
![image](https://user-images.githubusercontent.com/14121801/60184665-097acf00-985b-11e9-8a1e-a701fc1bea0e.png)
![image](https://user-images.githubusercontent.com/14121801/60184689-14cdfa80-985b-11e9-8e62-a77a422c99cd.png)
看來是第一行太長會導致他自動換行造成擠壓
看是否要將第一行過長改成...
或者是將左右再拉長一點有足夠空間
