### ISSUE TITLE
演講列表要列出額外講者

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycon.tw#561]
印象中之前的年份應該有程式可以抄，例如

https://tw.pycon.org/2017/en-us/events/talks/

**Comment by shunghsiyu** [comment]
![image](https://user-images.githubusercontent.com/6041291/60277013-50d28f80-992f-11e9-8867-69cf1b29fdbd.png)

這樣是已經已經有列出額外講者嗎？

**Comment by jneo8** [comment]
看起來已經有了？

**Comment by uranusjr** [comment]
但是像這篇就沒有，奇怪

https://tw.pycon.org/2019/en-us/events/talk/865701685220081908/

**Comment by uranusjr** [comment]
Fixed in #567.
