### ISSUE TITLE
Add activity schedule

### ISSUE THREAD

**Issue by yungyuc** [pycontw/pycon.tw#564]
The website doesn't have the time schedule for all activities, including but not limited to: speaker reception, pynight, sprint, tutorial.  I am not sure if all the activities will be held.  But if some will be held, having them their time shown on the website should be useful to attendees.  It may be particularly useful for oversee attendees to plan their trip.

**Comment by uranusjr** [comment]
I want to incorporate this into the overview page (#569), but have trouble coming up with texts for those events. Any idea would be extremely welcomed.

**Comment by tai271828** [comment]
Event ended. Close the ticket.
