### ISSUE TITLE
App 的議程表 URL

### ISSUE THREAD

**Issue by ji3g4kami** [pycontw/pycon.tw#574]
App 的議程是吃 web url，要先用 [schedule-json-generator](https://github.com/CCIP-App/schedule-json-generator) 產生 json 檔，然後放到 https 給 App 端用。
備註：使用 CCIP OPass App，要去 [OPass 設定檔生產器](https://portal.opass.app/) 發 PR。

**Comment by uranusjr** [comment]
議程 API：https://tw.pycon.org/2019/ccip/

麻煩再協助確認格式正確。
