### ISSUE TITLE
用Windows Run出現UnicodeDecodeError

### ISSUE THREAD

**Issue by winniepopu** [pycontw/pycon.tw#647]
#### Goal
修復UnicodeDecodeError的error

#### Description
昨天試著用Window 10 系統 run Server，發現最後會卡在UnicodeDecodeError
不確定是我環境問題還是windows系統的問題
想問有人是用windows run起來的嗎?

使用系統: window10 64位元
Branch : master , Django3 (都一樣的問題)

#### Error Message
  File "C:\Users\Winniepopu\AppData\Local\Programs\Python\Python36\lib\site- 
  packages\compressor\filters\base.py", line 188, in input
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 0: invalid start byte

#### Screenshots
![image](https://user-images.githubusercontent.com/15531846/74711530-1ff8ef00-525f-11ea-8259-671b99bf9fb2.png)

![image](https://user-images.githubusercontent.com/15531846/74712495-64858a00-5261-11ea-93f9-5e6ab6f52cef.png)

**Comment by uranusjr** [comment]
你看到的錯誤是 django-compressor/django-compressor#495，不過即使你解決了這個，後面還是會有其他的錯誤（kottenator/django-compressor-toolkit#11）。目前無解，請用 Docker 或 WSL 來跑。

**Comment by winniepopu** [comment]
好的感謝~正在嘗試中~

**Comment by vyach-vasiliev** [comment]
I had a similar error.
As it turned out, I forgot to install the **LESS** preprocessor.
I ran a command in the **CMD** and all worked: `npm install less -g`
