### ISSUE TITLE
英文會場地圖跑版

### ISSUE THREAD

**Issue by Lee-W** [pycontw/pycon.tw#650]
![Screen Shot 2020-02-22 at 12 41 55 PM](https://user-images.githubusercontent.com/5144808/75086567-d0713680-5570-11ea-84a8-3dcfa6919f1c.png)

**Comment by yychen** [comment]
已修正
![圖片](https://user-images.githubusercontent.com/484883/75564487-3553f180-5a87-11ea-820c-f3058e45c99f.png)
