### ISSUE TITLE
兩個會場要不要用不同顏色來標示？

### ISSUE THREAD

**Issue by Lee-W** [pycontw/pycon.tw#651]
![Screen Shot 2020-02-22 at 12 01 10 PM](https://user-images.githubusercontent.com/5144808/75086576-de26bc00-5570-11ea-9341-90545ec8d3a4.png)

**Comment by yychen** [comment]
這邊設計師已經有更新的設計了，我們近期會 update

**Comment by yychen** [comment]
新版長這樣唷！
![圖片](https://user-images.githubusercontent.com/484883/75564275-ceced380-5a86-11ea-8a46-600efd7b6944.png)
小圖示不同，但顏色還是一樣 orz
看一下覺得如何
(live reference https://staging.pycon.tw/2020/venue)
