### ISSUE TITLE
sublist 的 item 跟下一個 list item 太接近

### ISSUE THREAD

**Issue by Lee-W** [pycontw/pycon.tw#652]
不太確定這是不是刻意的設計，如果是的話請 Close 掉這個 issue 🙏

![Screen Shot 2020-02-22 at 12 15 20 PM](https://user-images.githubusercontent.com/5144808/75086583-f0a0f580-5570-11ea-9fc9-0b87925b15ca.png)

**Comment by yychen** [comment]
不是，內文的 style 有更新 (但還沒修 XDrz)
