### ISSUE TITLE
英數字型建議跟中文字型字重相同

### ISSUE THREAD

**Issue by kkshyu** [pycontw/pycon.tw#664]
由於目前看起來英數的字重比中文重（應該是字型的關係）
建議使用英數與中文字重接近的字型
不然閱讀上會很卡且不舒服，而且有連結處也會被忽略

在首頁上面較不明顯，像是關於頁面就有點讓人難以看完
https://staging.pycon.tw/2020/zh-hant/about/pycontw/

**Comment by yychen** [comment]
我們會調整字型。

**Comment by yychen** [comment]
We did some adjustment, but not good enough. Hopefully this would be better next year.
