### ISSUE TITLE
中文前端優化

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycon.tw#666]
幾個看一眼想到的問題

![Screenshot 2020-02-25 at 16 01 01](https://user-images.githubusercontent.com/605277/75228362-f99cfb80-57ea-11ea-9ee7-e7fee3c2f273.png)

* 行文格式統一：目前有些地方中英文之間有空格，有些沒空。
* 字型選擇雜亂。(#664)
* 右下背景的圖憑空被卡掉很讓人疑惑。（沒 inspect 不知道是圖本來就只有這樣還是區塊的問題）

**Comment by yychen** [comment]
文字格式的部份請 @Lee-W 看一下。字型與窗花切掉的部份會再修正，設計師已經給修正了還沒弄 :D
