### ISSUE TITLE
CfP: add onre more category "packaging"

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycon.tw#703]
To differentiate "python core" and "python internals" well.

**Comment by uranusjr** [comment]
I was thinking maybe also eliminate one of these or merge them into one category.

**Comment by tai271828** [comment]
@Lee-W  May you help us list all existing categories so people who are interested in this topic could get in the context more easily?

**Comment by Lee-W** [comment]
最佳實踐與慣例
社群
資料庫
資料分析
教育
嵌入式系統
金融科技
遊戲
圖像處理
其他
Python Core（語言本身、標準函式庫…）
Python 內部運作
物聯網
Python 函式庫
科學
資訊安全
系統管理
測試
網站框架

**Comment by Lee-W** [comment]
It can be found [here](https://github.com/pycontw/pycon.tw/blob/4d6d26d2db6abab94f1792010b3c95cf58ed6341/src/locale/zh_Hant/LC_MESSAGES/django.po#L77-L154).

**Comment by tai271828** [comment]
Thanks for sharing the information. My 2 cents (in order, best --> better):

1. Python Internals (packaging, dev env setup ...etc.)
2. Python Packaging (remove Python Internals)

"Python Internals" sounds very ambiguous for me.

BTW, I know the db of 2020 is an isolated one so I suppose we could feel free to change the category and won't impact the old data in the past years. Thank @yychen for what he foresaw!!

**Comment by uranusjr** [comment]
感覺流分類比較尷尬的類別：

* Python Core (要算 Python Internals 好像也說得過去)
* Python 函式庫 (要用函式庫做什麼？應該可以分到某一個其他分類)

個人覺得 dev env setup 可以算在 best practice。

**Comment by yychen** [comment]
@tai271828 我其實... 還沒做 @@" 但改 category (照理說) 不會影響到過去的資料, 因為它其實背後應該是個 VARCHAR 的 field... 所以應該沒問題。但我還是想一下要不要 isolate DB 好了 (Things are piling up)
