### ISSUE TITLE
Add "remote speak" option

### ISSUE THREAD

**Issue by Lee-W** [pycontw/pycon.tw#710]
Due to the outbreak of COVID-19, it would be better if we could ask the speakers whether they're ok with the virtual conference if the epidemic does not end by August.

Sample column:

![image](https://user-images.githubusercontent.com/5144808/76867750-ed173a80-68a0-11ea-9c9c-5cbbf97775b3.png)

**Comment by 18z** [comment]
### 中文文本：

* Title:  
遠端視訊演講 *

* Long Description:
因應新型冠狀病毒疫情，若到八月疫情未趨緩，是否同意以遠端方式進行演講？

* Option: 
是 / 否

### English Transcripts：

* Title: 
Remote Policy *

* Long Description:
Whether you agree to deliver the talk remotely if the epidemic (coronavirus) is still raging this August?

* Option:
Yes / No
