### ISSUE TITLE
[Sponsorship] Add prospectus description about COVID-19 plan

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycon.tw#722]
Many conferences were/are cancelled recently because of COVID-19. It will be great if we could have a plan for it as well. Topics should cover:

- [ ] What if we have gotten to sponsorship money and signed the contract? Refund partially?
- [ ] What's the prospectus if we turn the conference into a virtual one or cancel it?

**Comment by yuhow** [comment]
off line discussion
