### ISSUE TITLE
Update README.md DEPLOY.md

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycon.tw#728]
We have more and more new starter joining the development team. It will be great for them if we could have more step-by-step instructions in different scenarios.

**Comment by tai271828** [comment]
Hi @alice6373  I thought your part (db setup locally) is done, right?

**Comment by tai271828** [comment]
@macs1207  will help us update the github working flow instruction of the session "How to Contribute".

**Comment by alice6373** [comment]
Hi 泰祥：
對，但我有再想還有沒有需要補上連接postgres環境(local.env)與super user的指令在readme.md上...

櫻瀞 上

Taihsiang Ho <notifications@github.com> 於 2020年5月2日 週六 下午8:40 寫道：

**Comment by mattwang44** [comment]
Close this issue since we've reviewed the doc again and merged #965. `CONTRIBUTING.md` will be written after the workflow of the 2021 web squad is well-defined.
