### ISSUE TITLE
Locale zh-hant not working on local deployment home page

### ISSUE THREAD

**Issue by macs1207** [pycontw/pycon.tw#761]
## Environment
- Python: 3.8.2
- Django: 3.0.3

## Issue description
On my local environment, I set the "zh-hant" pattern in URL, but home page is still render English view.
Besides, other pages is normal working.

@yychen says the issue may caused by the path struct.

![image](https://user-images.githubusercontent.com/18455913/81192303-a1edee00-8fec-11ea-81a9-d1d2454e05f9.png)

**Comment by jp6ru8958958** [comment]
目前的解決方法是
```
python ./manage.py compilemessages
```
但是不曉得是不是我們想要的方式？
README.md提到的tox已經棄用了嗎？

**Comment by tai271828** [comment]
@jp6ru8958958   有意思，請問為什麼 `python ./manage.py compilemessages` 可以解決這個問題?

**Comment by jp6ru8958958** [comment]
```
python manage.py compilemessages
```
指令是把```/src/locale/_src/LC_MESSAGES/django.po```編譯成同路徑的```django.mo```(django本身執行會讀的檔案)

如果這個是我們要的翻譯方式的話，我想我們可以直接在README.md上修改一下說明並把有關tx(已棄用)那部份拿掉就好

**Comment by yychen** [comment]
對 XDD 這串好久了。 @tai271828 你還記得你有一個 commit 把 .mo 從 repo 砍光因為當時我們發現 deploy 的時候他會自己生成嗎? 應該就是這個問題。因為 compiled 的 mo 檔案不在 repo 裡面所以要自己弄。但如果 @mattwang44 幫忙那的那個 script 有加上的話應該就會自動有了。

**Comment by tai271828** [comment]
Oh right! So in my opinion...

1. Update the doc to issue `python manage.py compilemessages` or suggest developers to use matt's script
2. tx could be removed +1

**Comment by tai271828** [comment]
Oh cool. Github would close the issue automatically right after the fix of pull request is merged.
