### ISSUE TITLE
[Feature Request] House cleaning for unused or outdated branches

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycon.tw#765]
We have a lot of unused and/or outdated branches when time goes by for so many years. If we have a moment, it will be great to remove them.

**Comment by tai271828** [comment]
Let's list the candidates of branch to remove later. This comment will be a running note. Please comment in the following to let me know the branch should not be removed.

We are going to remove the following branches:

- [ ] pei-master
- [ ] django3
- [ ] colored-reviewer
- [ ] change-password
- [ ] cfp-category
- [ ] 2020-telegram-bot
- [ ] 2020-style
- [ ] 2019-pynight

**Comment by mattwang44** [comment]
I've deleted most old branches.
