### ISSUE TITLE
[Feature Request] Python 刈包/百香果活動 portal

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycon.tw#767]
We are going to have the exciting event! We may want to have a portal for it so we may leverage the traffic for more information.

**Comment by yychen** [comment]
我的想法是先開出一個 static page, 類似 https://tw.pycon.org/2020/zh-hant/sponsor/sponsor/ 贊助這一頁一樣, 先把頁面開出來, 然後 link 可以連得到。

我想 static page 的 link 就叫做
warmup-sessions/passion-fruit  <== 這樣

**Comment by jp6ru8958958** [comment]
# 第壹次Python NPF百香果 x 南投.py
![](https://i.imgur.com/FRIbiSE.png)
### Python NPF百香果是今年一個由Pycon Taiwan所籌備的小型線上會議，在疫情肆虐全球的情況下，我們希望藉由這樣的線上活動來拉近彼此間的距離，並利用此本次活動向大家揭露南投.py的神秘面紗！
* 活動時間:
> 2020/05/30 14:00
* 活動形式:
> Youtube 線上直播
* 線下聚會:
> 768藝術空間
*  連線資訊: 
> 請關注 [pycon Taiwan](https://www.facebook.com/pycontw/)及 [南投.py](https://www.facebook.com/%E5%8D%97%E6%8A%95python-113209870215893/)  Facebook粉專資訊!  Youtube直播連結會於當天發布於FB動態牆。直播結束後，會再將影片上傳至此。
* 主持人:
> 南投.py創辦人 - 林正敏
## 社群介紹:
* [南投.py](https://www.facebook.com/%E5%8D%97%E6%8A%95python-113209870215893/) 
> 2019年底，由南開科技大學副校長林正敏教授，號召、帶領並群聚著中台灣喜愛Python的人們。起初聚會地點在草屯768藝術空間，藉由768的公益性平台固定於每月舉行分享會，來自各行各業的大夥，無私地向大家分享自身經驗。在南投，人稱科技沙漠的地區，有著這一群人，為python貢獻己力，帶動產業連結，並為有意學習的大家，帶來一場無私、無限的學習地。
 
## 講者介紹:
* ![](https://i.imgur.com/Ossx5gR.png =50x50)Mosky
> Mosky 是個熱愛 open source 精神的 Python 工程師，也是 Pinkoi 的 Python Charmer，工作時和同事一起打造能夠買到獨特禮物的設計品購物平台。自從寫下人生第一支程式後，就難以忘懷以敘述為磚、邏輯為泥，堆砌出腦中藍圖的成就感，也熱愛分享自己所學，業餘時是 Python 課程講師，偶爾講點資料科學。也是數場國內外研討會的講者，包含臺灣的 PyCon、COSCUP、TEDxNTUST，以及在日本、新加坡、香港、韓國、馬來西亞等地的 PyCon。More: mosky.tw。 
* ![](https://i.imgur.com/CPxFpQx.png =50x50)Tzu-ping Chung
> TP 的職業生涯建立在開源軟體上，喜歡花費自己的精力讓這個世界更好。為了生活而寫過各式各樣的軟體，從嵌入式系統到 SPA 都是狩獵範圍，且只要有能力，就會盡量回饋社群。最近的空閒時間大多花在籌辦 PyCon Taiwan、貢獻核心 Python 工具、以及研究怎麼用 Python 與現代前端技術做網站。他有點太喜歡（人類）語言，常常扯到太多語言學和語音學，讓聊天內容變得無聊。
## 活動議程
| 時間 | 執行項目 |
| - | - |
| 14:00 - 14:05 | 活動開始 |
| 14:05 - 14:20 | 主持人開場與社群介紹－南投.py |
| 14:20 - 15:00 | 講者分享1 : Mosky－Python 的隱藏魔法：符號計算、統計到機器學習 |
| 15:00 - 15:40 | 講者分享2 : Tzu-ping Chung －pip install --unstable-feature=resolver |
| 15:40 - 16:00 | 活動結尾 |

**Comment by yucheng77** [comment]
Do we need English version?

**Comment by jp6ru8958958** [comment]
> @jp6ru8958958 Do we need English version?
> 
> 

就我所知是不需要

**Comment by yucheng77** [comment]
#785
