### ISSUE TITLE
[deployment] Cannot deploy on production environment

### ISSUE THREAD

**Issue by yychen** [pycontw/pycon.tw#790]
## Description
**docker-compose won't work**
Since [docker-compose.yml](https://github.com/pycontw/pycon.tw/blob/master/contrib/docker-compose.yml) is moved to the [contrib](https://github.com/pycontw/pycon.tw/tree/master/contrib) folder, the original deployment method `docker-compose up --build -d` at project root level does not work.

An alternative is to use `docker-compose -f contrib/docker-compose.yml up --build -d`, but I think it kind of lose the benefit of cutting the command short by using the default naming.

But either case won't work. Because in `docker-compose.yml`, it says to build `.` whereas the `Dockerfile` is actually at `..`. I think we can work out a better solution.

## Steps to Reproduce
1. Run `docker-compose up --build -d` at the project root directory (In this case, `~/web-projects/pycontw-2020` in the production / staging server)
2. You'll see the error message
```
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

Alternative step:
1. Run `docker-compose -f contrib/docker-compose.yml up --build -d`
2. You'll see the error message
```
Building web
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

## Expected Behavior
It should start building, recreate the image and run it.

## Actual Behavior
It did not build.

## Additional context
Or, should we run it inside the `contrib` folder? It seems a little bit weird to me, and I need to test it out because in my past experience, docker-compose kind of remember which folder you run it. Need to make sure if it causes any problem.

Can test it on the staging environment.

**Comment by tai271828** [comment]
Let me resolve in the following steps:

1. (short term) keep the folder of `contrib` for PR #783 by moving production files to the upper folder, or creating symbolic links for them. I personally prefer to use symbolic.
2. We may use this issue thread to keep discussion which kind of location convention we may want. Referring to those famous open source projects should help. (see the next comment for the collection of open source projects)

**Comment by tai271828** [comment]
# Projects with using `contrib` and `Dockerfile` is inside `contrib`

- [ ] xxx

# Projects with using `contrib` and `Dockerfile is NOT inside `contrib`

- [ ] xxx

# Projects without using `contrib`

- [ ] Django

**Comment by tai271828** [comment]
I will deliver step1 by the end of today to let us move forward to deploy production site.

**Comment by yychen** [comment]
> Let me resolve in the following steps:
> 
>     1. (short term) keep the folder of `contrib` for PR #783 by moving production files to the upper folder, or creating symbolic links for them. I personally prefer to use symbolic.

Looks good to me!

I actually deployed the latest code this morning. I just manually move the `docker-compose.yml` to upper level directory. So the repository in the production is temporary inconsistent to the one in github. But we'll fix it after we have a solution.

**Comment by mattwang44** [comment]
I think it's no longer an issue now. Will open a new issue if we got similar problems.
