### ISSUE TITLE
[Feature Request] Dropdown list for changing review stage

### ISSUE THREAD

**Issue by Lee-W** [pycontw/pycon.tw#795]
## Is your feature request related to a problem?
Currently, we need to manually change the value in `Django Registry > Entries`. based on [Proposal Review System Documentation](https://github.com/pycontw/pycon.tw/tree/master/src/reviews)

## Describe the solution you'd like
Let users choose the stages instead of setting values. We can make it a drop-down list.

## Describe alternatives you've considered
None

## Additional context
![圖片](https://user-images.githubusercontent.com/5144808/83963367-237cb880-a8d8-11ea-93b1-44a593caa41f.png)

## Invite the community to discuss and vote
Earn votes and support by involving the community and invite everybody to discuss your feature and
to vote for it (votes are +1 , 0 or -1 via adding a **thumbs-up/down**)

**Comment by yychen** [comment]
I think this is a duplicate issue to https://github.com/pycontw/pycon.tw/issues/727 and the corresponding PR https://github.com/pycontw/pycon.tw/pull/782

**Comment by mattwang44** [comment]
duplicated issue
