### ISSUE TITLE
[Feature Request] Create PyCon TW 2020 Talk Schedule 

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycon.tw#813]
We have the talk list now https://staging.pycon.tw/2020/en-us/events/talks/ and we will soon need a talk schedule / program table like this https://tw.pycon.org/2019/en-us/events/schedule/

**Comment by jneo8** [comment]
According to @yychen saying. We are going to use 2019's design for 2020?
OR do we have the new design template

**Comment by yychen** [comment]
Yeah, I'm thinking using 19 design with 20 style (color theme), or only minor adjustments. But if the design team have other ideas... I think I'm open to other possibilities :D

**Comment by mattwang44** [comment]
Do we have any update on this (design part)?
Just realized this task can be much harder than I thought after tracing the work in 2019 XD.

**Comment by yychen** [comment]
Thanks @flynnhou for your hard work! It looks very nice!
