### ISSUE TITLE
[Feature Request] Make the "register" page available

### ISSUE THREAD

**Issue by yychen** [pycontw/pycon.tw#819]
## Is your feature request related to a problem?
It's about time to sell the tickets. We need to make the register page available.

## Describe the solution you'd like
Copy the template from 2019's website and make the URL accessible. And then restyle it based on the visual Design Team provides.

## Additional context
A reference to 2019's page: https://tw.pycon.org/2019/zh-hant/registration/ticket-info/

**Comment by yucheng77** [comment]
#821
