### ISSUE TITLE
[Feature Request] Keynote Page

### ISSUE THREAD

**Issue by yychen** [pycontw/pycon.tw#838]
## Is your feature request related to a problem?
Keynote page should be ready. It should have a description of the keynote speaker and the presentation.

## Describe the solution you'd like
Copy the keynote page template from 2019 and change the style to 2020 theme.

## Additional context
This would be a collaboration between the Design and Program team. A draft page can be copied first and make it available to the Design team so they can work on the style for this year. Program team member can work on the data in parallel.

**Comment by thicyo** [comment]
`
<style type="text/css">
.keynotes-page .media figcaption {
    color: #612d2e;//new 
}

.tabbing > .tabs > li.active {
    background: #E23728;//new 
    color: #ffffff;//new 
}

.tabbing > .tabs > li {
    flex: 1 1 112px;
    min-width: 64px;
    margin: 0 4px;
    padding: 8px 0;
    border-radius: 2px 2px 0 0;
    background: rgba(226, 55, 40, 0.1);
    text-indent: 0;
    text-align: center;
    font-weight: normal;
    color: #612d2e;//new 
}

.tabbing > .tabs > li:not(.active):hover {
    background: #E23728;//new 
    color: #fff;//new 
}

.tabbing.enabled > .tabs ~ * {
    border-top: 2px solid #d0908a;//new 
}
</style>
`

![screenshoot_events_keynotes](https://user-images.githubusercontent.com/20593265/88918277-c67bfe00-d29b-11ea-9597-adca01e82b83.png)

**Comment by yychen** [comment]
For the colors and font, you can take a look at `src/static/pycontw-2020/styles/_palette.scss` first to see if the color matches the predefined ones. 再麻煩你了 @shunghsiyu
