### ISSUE TITLE
[Feature Request] Tutorial Page

### ISSUE THREAD

**Issue by yychen** [pycontw/pycon.tw#839]
## Is your feature request related to a problem?
Tutorial page should be ready. It should have a brief description of the tutorials.

## Describe the solution you'd like
Copy the keynote page template from 2019 and change the style to 2020 theme.

## Additional context
This would be a collaboration between the Design and Program team. A draft page can be copied first and make it available to the Design team so they can work on the style for this year. Program team member can work on the data in parallel.

**Comment by thicyo** [comment]
![screenshot_Tutorial Page](https://user-images.githubusercontent.com/20593265/88697378-11303580-d137-11ea-88c3-fa1856145773.png)

`.box {
    border: solid 1px #6A3F3B; //new style
    border-radius: 5px;
    overflow: hidden;
}

.box .box-title {
    margin: 0;
    padding: 0.66667rem 1rem;
    background-color: #6A3F3B; //new style
    color: #ffffff;
    line-height: 150%;
    font-size: 1.25rem;
    font-weight: 400;
}

.box .box-control > * {
    color: #502526;
    font-family: "Philosopher", "Noto Sans TC", "sans-serif";
    font-size: 1.25rem;
    font-weight: normal;
    text-align: center;
    text-decoration: none;
    flex: 1;
    border-top: solid 1px #502526; //new style
    line-height: 48px;
    text-align: center;
    font-weight: 400;
}

.box .box-control > a:hover {
    background: #6A3F3B; //new style
    color: #ffffff;
}`

**Comment by yychen** [comment]
For the colors and font, you can take a look at `src/static/pycontw-2020/styles/_palette.scss` first to see if the color matches the predefined ones. 再麻煩你了 @freddy50806
