### ISSUE TITLE
[Feature Request] Development Sprint Page

### ISSUE THREAD

**Issue by yychen** [pycontw/pycon.tw#842]
## Is your feature request related to a problem?
Development sprint page should be ready. It should have all the details to the event.

## Describe the solution you'd like
Copy the development sprint page template from 2019, update the content and change the style to 2020 theme.

## Additional context
The 2019 sprint page for reference is hidden from the menu. You can take a look via https://tw.pycon.org/2019/zh-hant/events/sprints/.

This would be a collaboration between the Design and Program team. A draft page can be copied first and make it available to the Design team so they can work on the style for this year. Program team member can work on the data in parallel.

**Comment by yychen** [comment]
@Lee-W 這邊要麻煩議程組生文案 (中文/英文)。

**Comment by Lee-W** [comment]
Development Sprint 已經完成了！
https://docs.google.com/document/d/1A-fNFpjPSDh1f2Ea_Uoo070YAn9narw9ImP0KEgtvlY/edit
