### ISSUE TITLE
[Feature Request] Open Space Page

### ISSUE THREAD

**Issue by yychen** [pycontw/pycon.tw#843]
## Is your feature request related to a problem?
Open space page should be ready. It should have a detail description of this activity.

## Describe the solution you'd like
Copy the open space page template from 2019 and change the style to 2020 theme.

## Additional context
This would be a collaboration between the Design and Program team. A draft page can be copied first and make it available to the Design team so they can work on the style for this year. Program team member can work on the data in parallel.

**Comment by yychen** [comment]
@Lee-W 這邊要麻煩議程組生文案 (中文/英文)。

**Comment by MadRex2000** [comment]
其實他們已經有產文案了 不過有一部分的的英文沒還沒翻譯完成。
