### ISSUE TITLE
[Feature Request] Add staff page

### ISSUE THREAD

**Issue by yychen** [pycontw/pycon.tw#849]
## Is your feature request related to a problem?
Staff page should be ready. It should have all staff listed.

## Describe the solution you'd like
Copy the staff page template from 2019 and change the style to 2020 theme.

## Additional context
Need to contact all team leads and get the names.

**Comment by tai271828** [comment]
Recruitment team:
- tai271828
- catcatcatcat
- Rex Wu
- Wee Lee

**Comment by Rockhung** [comment]
Finance team:

Rock
Timchen

**Comment by Lee-W** [comment]
Program Committee: 

李唯 (Wei Lee)
--
TP
Frank
Jason
Adrian
Kun Yu
PoChun
pinglin
Peihsaun
Wun Hua
駿偉
小知
Cicilia Lee
Pearlie Lin
Annie Bu
Ming-Hung Hung
Jordan
Gina
KK
Sonia Wu
petertc
Yider
Gina Wang
Kyle

**Comment by Lee-W** [comment]
Reviewer

Kir Chou
Cicilia Chia-ying Lee
廖偉涵 Adrian Liaw
劉純睿（阿吉）
李昱勳
Ping Chu Hung
Liang-Bo Wang
Jason
Chi-Hsuan Huang
Cheng-Lung Sung (宋政隆)
Shuen-Huei Guan
Jack Pan
曾君宇
郭學聰 (Hsueh-Tsung Kuo)
Zong-han, Xie
Jian-Ming Huang
Kilik Kuo
Kuo-tung Kao
席恩
Malo
古宣佑 Hsuanyu
Spin Lai
petertc
王文傑
Kelly Chang
Sammy Fung
sosorry
Shuhsi Lin
JunWei Song
何泰祥 Taihsiang Ho (tai271828)
Ing Wei Tang
Thinker
柯維然
Tzu-ping Chung
Wei Lin
李唯 (Wei Lee)
Stanley Huang
KunYu Chen
Frank
Keith Yang
Yen
Jimmy Lai

**Comment by yychen** [comment]
開發組 (Dev)
Tom Chen
tai
Wei-Hsiang (Matt) Wang
Rex
阿嘉
Alice
Macs
Maliao Guo
Annie Bu
Pearlie
GTB
Jeremy Sung
Leon Fu
Josix
SHY
Fliss

**Comment by yychen** [comment]
OPass
Denny Huang
腹黒い茶

**Comment by mattwang44** [comment]
[Photography]

Andy
Deimos
小草
大鳥
家維
阿緯
毓鎂

**Comment by kohsintsai** [comment]
PR

- Ko-Hsin Tsai
- 米方 
- Hane
- Zonghan
- Alvin Lin
-
