### ISSUE TITLE
[Feature Request] Change front page sponsor logo style

### ISSUE THREAD

**Issue by yychen** [pycontw/pycon.tw#858]
## Is your feature request related to a problem?
Update the sponsor logo style.

## Describe the solution you'd like
Change the style based on the design provided.

## Additional context
The design team will provided the design in the comments below.

**Comment by thicyo** [comment]
[主要變更項目]

1. 對調順序：贊助logo 和關於pycon的block 
![示意圖1](https://user-images.githubusercontent.com/20593265/89610212-8b398a80-d8ac-11ea-90e9-24700e9a107e.png)

2. 加標題：贊助商logo 要加h2標題
![螢幕快照 2020-08-07 下午12 51 09](https://user-images.githubusercontent.com/20593265/89610304-bd4aec80-d8ac-11ea-82cb-04a01bc804ac.png)

3. 新增class: 請新增一個class Selector  加到對應的component裡 
.main-content.full-width-bg {
    background: #f4af9e;
    margin: 0px;
    padding-top: 80px;
}

![螢幕快照 2020-08-07 下午12 42 02](https://user-images.githubusercontent.com/20593265/89609832-8c1dec80-d8ab-11ea-9f16-7c09f8b6543e.png)

4. 浮水印排版：浮水印請移到 index-partners 這個section裡
![螢幕快照 2020-08-07 下午12 55 18](https://user-images.githubusercontent.com/20593265/89610536-5548d600-d8ad-11ea-8d55-cdce88f6fa8f.png)

---
## css 更新

`
@media (min-width: 768px){
    .menu-navbar-desktop {
        margin: 0 auto 50px;
        max-width: 1160px;
        padding: 0;
    }
}

.index-partners > .container > .grid-layout > .partner-container > a img, .index-partners > .container > .grid-layout > .partner-container > a > span {
    margin: 40px 0px;
    position: relative;
    z-index: 1;
    width: 100%;
    /* max-width: 274px; */
    /* max-height: 125px; */
    line-height: 64px;
    vertical-align: middle;
    font-size: 175%;
}

.index-partners {
    padding: 20px 40px 80px 40px;
    margin: 0 auto;
    max-width: 1160px;
    padding: 0;
    margin-bottom: 100px;
}

.index-partners > .container > .grid-layout > .partner-container {
    background-color: #ffffff6e;
    border: 1px solid #ffffff00;
    display: flex;
    height: 268px;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    padding: 5px;
    position: relative;
    overflow: hidden;
}

.index-partners > .container > .grid-layout > .partner-container > span {
    position: absolute;
    top: 0.7em;
    left: 0.7em;
    z-index: 100;
    text-shadow: 1px 1px 1px #ffffff;
    font-weight: bolder;
}

@media (max-width: 760px)
.index-partners > .container > .grid-layout {
    grid-template-columns: repeat(1, 290px);
}

.index-partners > .container > .grid-layout {
    display: grid;
    grid-template-columns: repeat(3, 290px);
    -webkit-column-gap: 40px;
    -moz-column-gap: 40px;
    column-gap: 40px;
    row-gap: 40px;
    margin: 40px;
}

.index-partners > .container {
    max-width: max-content;
    margin: 0 auto;
    padding-bottom: 8px;
}

.main-content.full-width-bg {
    background: #f4af9e;
    margin: 0px;
    padding-top: 80px;
}
`
