### ISSUE TITLE
[Feature Request] Community Track Option

### ISSUE THREAD

**Issue by yychen** [pycontw/pycon.tw#879]
## Is your feature request related to a problem?
We need the attendees to pre-select which community track they want to go, and make sure the amount of attendees does not exceed the maximum capacity of each venue. Since it is not easy to switch to another track due to the distance of each venue, it would be better that we do this proactively.

## Describe the solution you'd like
A page that shows all the info of each track, including the venue, the local community it has, the talks.
There would be an "attend" button for each track, and it will show the capacity of the venue and how many people have chosen. I think we can have a soft limit and hard limit. The hard limit would be the max capacity, and the soft limit might be something like 80% of the hard limit.

If the number exceeds the soft limit, give it a yellow light, or a red light if it exceeds the hard limit, else, give it a green light. Something like that.

Attendees can switch track anytime they want, but no matter what, the numbers is a guidance to make the decision. It is also a helper to show what choice the attendee made, as a reminder.

I think we can create a django app for this, and two models should be created, `Venue` and `Choice`. The key to bind the attendee is the KKTIX hash/token (驗證碼) which is available in the OPass app, and also when we send the event notice letter.

## Describe alternatives you've considered
If we can not make it on time, we'll just create a simple HackMD or Github wiki page for the attendees to register themselves.

## Additional context
We've discussed this back and forth with @Lee-W, just hope that we can make it on time! Right? @mattwang44  (Finger crossed)

## Invite the community to discuss and vote
Earn votes and support by involving the community and invite everybody to discuss your feature and
to vote for it (votes are +1 , 0 or -1 via adding a **thumbs-up/down**)

**Comment by mattwang44** [comment]
> If the number exceeds the soft limit, give it a yellow light, or a red light if it exceeds the hard limit, else, give it a green light.
how about set the soft limit to be 80% of the venue capacity?

**Comment by yychen** [comment]
> > If the number exceeds the soft limit, give it a yellow light, or a red light if it exceeds the hard limit, else, give it a green light.
> 
> how about set the soft limit to be 80% of the venue capacity?

Sounds good to me.

**Comment by yychen** [comment]
@Maliaotw Please add the traffic information to the page, thanks :D https://docs.google.com/document/d/1YItW-XjHEbHPwJxes0CAOQotGD2-fYn2QMQMcgxp0EE/edit

**Comment by yychen** [comment]
![圖片](https://user-images.githubusercontent.com/484883/91325674-0fb96200-e7f6-11ea-836f-a544aee192ef.png)
然後，這圖片上面有一個 `/50`，請幫我加上，舉例，有 25 個人選這個場地，變成 `25/50`。

然後有三種顏色，80% 是一個 soft limit，也就是說如果是低於 50 x 80% = 40 的話，用一般的黑色，
如果介於 40-50，用黃色的，如果超過 50 就用紅色的字。
