### ISSUE TITLE
[Feature Request] Display (approximate) time next to each community track entry

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycon.tw#916]
## Is your feature request related to a problem?

Quote from Discord:

> clyang: one suggestion. It would be much easier for participants to know when the talk starts if the time is added to talk's title.

## Describe the solution you'd like

Use `<dl>` instead of `<ol>` to put the time at the left of the title.

The time information should be available in the event model (same as #915).

## Describe alternatives you've considered

Use tables? But `<table>` is not responsive-friendly and I prefer `<dl>`.

## Additional context

I made a quick mockup:

![Screenshot 2020-08-31 at 15 13 39](https://user-images.githubusercontent.com/605277/91692884-bc039b80-eb9c-11ea-8884-208f4b7739f2.png)

**Comment by yychen** [comment]
It is deployed to the production site. The detailed time table for each community track is displayed just below the venue picture, in the agenda section. Thanks for making this advice, it makes the website much better 👍
