### ISSUE TITLE
[Tutorial] Tutorial detail page return 500

### ISSUE THREAD

**Issue by mattwang44** [pycontw/pycon.tw#928]
## Description
Cannot access the tutorial detail page

## Steps to Reproduce
1. Go to `https://tw.pycon.org/2020/zh-hant/conference/tutorials/`
2. Click on the button below the description of each tutorial

## Expected Behavior
Should show tutorial detail page

## Actual Behavior
All three returns 500

**Comment by yychen** [comment]
I'd give this P0 though XD Anyway, thanks for the effort.=
