### ISSUE TITLE
[Feature Request] Help put keynote slides into the keynote page

### ISSUE THREAD

**Issue by yychen** [pycontw/pycon.tw#944]
## Is your feature request related to a problem?
We should be able to put keynote slides on the keynote page.

## Describe the solution you'd like
Add a item to the original json data structure.

## Describe alternatives you've considered
Nope.

## Additional context
This was once on the website, but it was taken out through these years.
And, the first one to put is the slides for Mariatta's talk https://speakerdeck.com/mariatta/oops-i-became-an-open-source-maintainer

Sample: https://github.com/pycontw/pycon.tw/blob/master/src/static/pycontw-2018/assets/keynotes/info.json

**Comment by mattwang44** [comment]
close by #946 & #970
